"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.errorUtils = exports.stackUtils = exports.theme = void 0;
const tslib_1 = require("tslib");
const errorsApi = (0, tslib_1.__importStar)(require("./errors"));
const errorUtils = (0, tslib_1.__importStar)(require("./errorUtils"));
exports.errorUtils = errorUtils;
const stackUtils = (0, tslib_1.__importStar)(require("./stackUtils"));
exports.stackUtils = stackUtils;
var errTemplate_1 = require("./errTemplate");
Object.defineProperty(exports, "theme", { enumerable: true, get: function () { return errTemplate_1.theme; } });
(0, tslib_1.__exportStar)(require("./errors"), exports);
(0, tslib_1.__exportStar)(require("./errorTypes"), exports);
exports.default = errorsApi;
